// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_lh4IAAwQU8PvmjbzXGs8qEwVBOIPxE8',
    appId: '1:884400775767:web:4d74983e84040c0d31f912',
    messagingSenderId: '884400775767',
    projectId: 'f2-material',
    authDomain: 'f2-material.firebaseapp.com',
    storageBucket: 'f2-material.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB27sHoAi6R5026O1Dmk6BTrLk1AH01hjk',
    appId: '1:884400775767:android:72233ee67796a02c31f912',
    messagingSenderId: '884400775767',
    projectId: 'f2-material',
    storageBucket: 'f2-material.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTrKR_nH9z9nXuiO9lZU9S88AxczcZaaQ',
    appId: '1:884400775767:ios:bf5f88be7736dfea31f912',
    messagingSenderId: '884400775767',
    projectId: 'f2-material',
    storageBucket: 'f2-material.firebasestorage.app',
    iosBundleId: 'com.f2telecom.f2Material',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTrKR_nH9z9nXuiO9lZU9S88AxczcZaaQ',
    appId: '1:884400775767:ios:bf5f88be7736dfea31f912',
    messagingSenderId: '884400775767',
    projectId: 'f2-material',
    storageBucket: 'f2-material.firebasestorage.app',
    iosBundleId: 'com.f2telecom.f2Material',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_lh4IAAwQU8PvmjbzXGs8qEwVBOIPxE8',
    appId: '1:884400775767:web:89334dd54513a5a031f912',
    messagingSenderId: '884400775767',
    projectId: 'f2-material',
    authDomain: 'f2-material.firebaseapp.com',
    storageBucket: 'f2-material.firebasestorage.app',
  );
}
